/* Tokens */
#define _boolean            01
#define _break              02
#define _class              03
#define _double             04
#define _else               05
#define _extends            06
#define _for                07
#define _if                 08
#define _implements         09
#define _int                10
#define _interface          11
#define _new                12
#define _newarray           13
#define _null               14
#define _println            15
#define _readln             16
#define _return             17
#define _string             18
#define _this               19
#define _void               20
#define _while              21
#define _plus               22
#define _minus              23
#define _multiplication     24
#define _division           25
#define _mod                26
#define _less               27
#define _lessequal          28
#define _greater            29
#define _greaterequal       30
#define _equal              31
#define _notequal           32
#define _and                33
#define _or                 34
#define _not                35
#define _assignop           36
#define _semicolon          37
#define _comma              38
#define _period             39
#define _leftparen          40
#define _rightparen         41
#define _leftbracket        42
#define _rightbracket       43
#define _leftbrace          44
#define _rightbrace         45
#define _intconstant        46
#define _doubleconstant     47
#define _stringconstant     48
#define _booleanconstant    49
#define _id                 50
